'use client';
import type React from 'react';
// import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
import Footer from './components/footer';
import { useState } from 'react';
import Loader from './components/loader';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

// const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [loading, setLoading] = useState(true);

    // useEffect(() => {
    //     setTimeout(() => {
    //         setLoading(false);
    //     }, 5000);
    // }, []);

    return (
        <html lang='en'>
            <head>
                <title>Inkwellmedia Agency</title>
                <meta
                    name='description'
                    content='Inkwellmedia Agency - Your trusted partner in media solutions.'
                />
                <meta
                    name='keywords'
                    content='Ad Making Agency, Media Solutions, Advertising, Marketing, Creative Agency'
                />
                <meta name='author' content='Inkwellmedia Agency' />
                <meta
                    property='og:title'
                    content='Inkwellmedia Agency - Ad Making Experts'
                />
                <meta
                    property='og:description'
                    content='Inkwellmedia Agency - Your trusted partner in media solutions and ad making.'
                />
                <meta property='og:image' content='/path/to/your/image.jpg' />
                <meta
                    property='og:url'
                    content='https://www.inkwellmedia.com'
                />
                <meta name='twitter:card' content='summary_large_image' />
                <meta
                    name='twitter:title'
                    content='Inkwellmedia Agency - Ad Making Experts'
                />
                <meta
                    name='twitter:description'
                    content='Inkwellmedia Agency - Your trusted partner in media solutions and ad making.'
                />
                <meta name='twitter:image' content='/path/to/your/image.jpg' />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1B1B1B]`}
            >
                {loading && (
                    <Loader
                        companyName='Inkwellmedia Agency'
                        loading={loading}
                        setLoading={setLoading}
                    />
                    // <div className='flex items-center justify-center h-screen'>
                    //     <div className='text-2xl font-bold text-[#fa8128] animate-pulse'>
                    //         Inkwell Media - Loading...
                    //     </div>
                    // </div>
                )}
                {!loading && (
                    <>
                        <Navbar />
                        {children}
                        <Footer />
                    </>
                )}
            </body>
        </html>
    );
}
